### ISSUE TITLE
Font & Colour for H2s and H3s in content

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/VON-ESC#154]

**Comment by ccmorris** [comment]
please be more specific

**Comment by tgascoigne14** [comment]
Font on staging site

![Screen Shot 2019-08-12 at 2 35 22 PM](https://user-images.githubusercontent.com/8631079/62889235-f474d500-bd0e-11e9-8f17-84f1897675e8.png)

Font in design 

![Screen Shot 2019-08-12 at 2 37 20 PM](https://user-images.githubusercontent.com/8631079/62889267-035b8780-bd0f-11e9-9a64-814e01269652.png)

Font on staging site

![Screen Shot 2019-08-12 at 2 38 43 PM](https://user-images.githubusercontent.com/8631079/62889296-12dad080-bd0f-11e9-9c96-f749d9ae8699.png)

Font in design

![Screen Shot 2019-08-12 at 2 38 32 PM](https://user-images.githubusercontent.com/8631079/62889320-1e2dfc00-bd0f-11e9-99f4-86aa8b9543bc.png)
